### ISSUE TITLE
 no CUDA GPUs Available

### ISSUE THREAD

**Issue by ProcopioPi** [n00mkrad/text2image-gui#40] opened 2022-12-05 02:10 UTC
I have an RTX 4090 and it says no CUDA GPUs Available, It is running on Windows 10 Pro with 128gb of RAM

**Comment by n00mkrad** [comment] 2022-12-05 04:51
Duplicate of https://github.com/n00mkrad/text2image-gui/issues/37#issuecomment-1336633740

**Closed by n00mkrad** 2022-12-05 04:51 UTC
